### ISSUE TITLE
Total Level compatibility with genMDM Editor

### ISSUE THREAD

**Issue by 2xAA** [rhargreaves/mega-drive-midi-interface#26]
Hey,

This is fantastic work!
I've been working on an editor for genMDM (https://github.com/2xAA/genmdm-editor) and I just picked up an Everdrive to try this project out.

Checking compatibility with my editor and it seems the Total Level CCs are being interpreted as 127-0 when they should be inverted for genMDM compatibility (0 being quietest and 127 being loudest).

I'm not sure if you'd be willing to invert the CC at this stage in the project, but maybe adding a genMDM compatibility flag somewhere in SysEx might be a neat solution?

Looking forward to your reply,
Sam

P.S. - I'm also in London, usually free if you wanna chat chiptune/music/code!

**Comment by rhargreaves** [comment]
Sounds like a sensible option to have; I'll look into it!

**Comment by rhargreaves** [comment]
[New SysEx command](https://github.com/rhargreaves/mega-drive-midi-interface/wiki/Configuration-&-Advanced-Operations) released in v1.7

**Comment by 2xAA** [comment]
@rhargreaves Thank you so much, this works perfectly.

Could I suggest updating the SysEx page to display the numbers in "full" hex notation? (e.g. `0x00 0x22 0x77 0x07 0xXX`)

I was a bit confused why my decimals weren't working until I looked at the first SysEx command on the page and realised my mistake as none of the other SysEx commands have any hex-specific characters.

**Comment by rhargreaves** [comment]
Good suggestion! I've clarified that the column of SysEx codes should be read in hexadecimal. Thanks
