### ISSUE TITLE
Note Portamento/Glide

### ISSUE THREAD

**Issue by 2xAA** [rhargreaves/mega-drive-midi-interface#39]
Feature request:

A portamento/glide toggle for each channel would be excellent.
A CC value, set to 0 is glide off, and 1-127 sets the speed of the glide maybe?

I can do this with MIDI but that takes up a significant amount of bandwidth.
I guess with pitch-bend already implemented, that's a start.

**Comment by rhargreaves** [comment]
Interesting idea. Is there an existing MIDI device which has an implementation for something like this?

**Comment by 2xAA** [comment]
It's not part of the MIDI spec, but plenty of synths implement it.

This YM2149 synth has it, for example:
https://github.com/trash80/Ym2149Synth

The DX7 has it as well, I'm sure other Yamaha synths of the era also did.

**Comment by rhargreaves** [comment]
This actually might be a really nice feature to have. I'm thinking:

* **Monophonic glide** for now (per channel). Polyphonic can be achieved through sending respective notes to the other channels. It would be lovely if polymorphic mode supported it in future, but I can see that being a lot more complex to implement right off the bat.
* **Legato glide** - whereby notes glide only if a note is played over the top of another note. Notes played when no other note is active will not glide. I think this makes the most intuative sense and is probably the one most people would use?
* **Linear constant rate (LCR)** vs **linear constant time (LCT)**. LCR is probably the simplest to start off with, but I can see applications for both. Maybe could be switched in future via SysEx.
* **Linear vs exponential**. Linear probably easiest and most commonly used.

Relevant CCs:

* CC 65 - Portamento on/off
* CC 5 - Portamento speed/rate

How does that sound? I don't really have direct experience with synths with portamento - I used [this video](https://www.youtube.com/watch?v=7hjhkPhxQLc) to get an idea of what support synths typically had!

**Comment by 2xAA** [comment]
Cool - sounds like a great plan!
And yes, a legato linear glide is pretty common I would say.

**Comment by rhargreaves** [comment]
Implemented in [v1.22](https://github.com/rhargreaves/mega-drive-midi-interface/releases/tag/v1.22)
