### ISSUE TITLE
Note Detune/fine-tune

### ISSUE THREAD

**Issue by 2xAA** [rhargreaves/mega-drive-midi-interface#41]
Feature request:

Synths often have the ability to detune their channels, which give great phasing effects for two channels playing with the same voice, called "unison".

Would it be possible to add this to MDMI?

**Comment by rhargreaves** [comment]
Yeah that sounds doable. The underlying changes I've had to make to accommodate portamento go nicely into providing a "fine-tuning" feature.

Initial thoughts would be to use CC 85. Value 0 would tune to -63 cents, and 127 would be 64 cents. Value 64 would be standard tuning.

**Comment by 2xAA** [comment]
Sounds great, thank you for taking the time!

**Comment by rhargreaves** [comment]
Implemented in [v1.23](https://github.com/rhargreaves/mega-drive-midi-interface/releases/tag/v1.23)
