### ISSUE TITLE
Can i make it with Arduino UNO?

### ISSUE THREAD

**Issue by starrpark** [rhargreaves/mega-drive-midi-interface#44]
I have an Arduino UNO R3 board. Can i send serial data to port 2 with Arduino? If yes, how do i send midi serial through Arduino?

**Comment by rhargreaves** [comment]
I'm afraid I have no experience using an Arduino. If you're looking to send serial data to the Mega Drive I would recommend taking a look at my [serial port](https://github.com/rhargreaves/mega-drive-serial-port) project which explains how to wire up and test communication with the controller port. Note that using the controller port this way is not as fast as using the USB port of a EverDrive cartridge and typically cannot handle multi-channel MIDI data too well.
